name: Go Lint & Test Checking

on:
  pull_request:
    branches: [main]
    paths: [cmd/**]
  push:
    branches: [main]
    paths: [cmd/**]

env:
  go-version: '1.24'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.2.0
        with:
          go-version: ${{ env.go-version }}

      - name: Run tests
        run: make go-test

      - name: Check gofmt
        run: make go-check

      - name: Run go vet
        run: go vet ./cmd/...

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.2.0
        with:
          go-version: ${{ env.go-version }}

      - name: Run tests
        run: make go-test
