name: Python Ruff and Test Checking

on:
  pull_request:
    branches: [main]
    paths: [script/**]
  push:
    branches: [main]
    paths: [script/**]

env:
  python-version: "3.12"

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        run: make install

      - name: Check Ruff formatting
        run: make py-check

  test:
    runs-on: ubuntu-latest
    needs: ruff

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make py-test
