name: Python Ruff and Test Checking

on:
  pull_request:
    branches: [main]
    paths: [script/**]
  push:
    branches: [main]
    paths: [script/**]

env:
  python-version: "3.10"

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions/setup-python@v6.1.0
        with:
          python-version: ${{ env.python-version }}

      - name: Install Ruff
        run: pip install ruff

      - name: Check Ruff formatting
        run: ruff check script/ --diff

  test:
    runs-on: ubuntu-latest
    needs: ruff

    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions/setup-python@v6.1.0
        with:
          python-version: ${{ env.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python3 -m pytest script/
